### ISSUE TITLE
Search service should support basic Autocomplete

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-search#24]
**Acceptance Criteria**
- [ ] How do we prove this is working on the search service?  CURL examples?
- [ ] Should return up to the 10 more accurate suggestions for the current word being typed.
- [ ] Search service will respond with data once 3 or more consecutive characters are passed as a parameter.
- [ ] Result suggestions should be in JSON format with up to 10 correctly spelled suggestions.

**Comment by farahfarahmand** [comment]
Once three letters of a search word is typed, up to 10 suggested word display. Observed that none of the suggested words can be selected.
